const express = require("express")
const router = express.Router()
const userController = require("../controller/userController")
const auth = require("../middleware/auth.js")
// router.get("/", function (req, res) {
//   res.send("Wiki home page")
// })
router.post("/register", userController.add)
router.get("/getAll", userController.getdata)
router.post("/login", userController.login)
router.get("/userAlldata/:id", auth, userController.getALLData)
router.get("/userProfile/:id", auth, userController.getProfile)
router.get("/userEdit/:id", auth, userController.editUser)
router.put("/userEdit/:id", auth, userController.updateUser)
router.delete("/userDelete/:id", auth, userController.deleteUser)
router.post("/request/release", auth, userController.sendRequest)
// router.get("/release", userController.getRequest)

router.post("/realeasesUser", auth, userController.realeasesUser)
router.post("/shareMarketOrg", auth, userController.shareMarketOrg)
router.get("/shareMarketOrg", auth, userController.getShareMarketOrg)
router.post("/buySharesByUser", auth, userController.buySharesByUser)
router.get("/buySharesByUser", auth, userController.getbuySharesByUser)
router.post("/sharebiding", auth, userController.sharebiding1)
router.get("/sharebiding", auth, auth, userController.getShareBiding)
router.post("/addHighestBiding", auth, userController.addHighestBiding)
router.get("/getHighestBiding", auth, userController.getHighestBiding)
router.get("/getWinner", userController.getWinner)
router.post("/winerCountDown", userController.winerCountDown)
router.get("/purchaseAvlTime", userController.purchaseAvlTiming)
router.post("/purchaseBid", userController.purchaseBid)
router.post("/removeAllBids", userController.removeAllBids)

router.delete("/delete/realeasesUser/:id", userController.deleteReleaseUser)

module.exports = router
